---
- hosts: all
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest
  - name: service
    service:
     name: httpd
     state: started
     enabled: yes
   - name: wget
     shell: cd/var/www/html; wget https://github.com/dineshkumar-ravisekar/assiss-ziff-26dec/blob/master/file.yml
     mode: 0755
     
    
  
